.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,7 +28,14 @@ runs:
 
         echo "DFX_VERSION is $DFX_VERSION"
 
-        sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
+        sh -ci "$(curl -fsSL --connect-timeout 1 https://internetcomputer.org/install.sh)"
+        # --retry 10  --retry-all-errors
+        #if output=$(curl --fail --silent --show-error --location --connect-timeout 5 https://internetcomputer.org/install.sh); then
+        #  sh -c "$output"
+        #else
+        #  echo "Failed to download install script."
+        #  exit 1
+        #fi
     - name: Set up path (linux)
       shell: sh
       if: runner.os == 'Linux'
