feat: auto mode: inspect dfx.json for dfx version (#6)

diff --git a/.github/workflows/dfx-action.yml b/.github/workflows/dfx-action.yml
--- a/.github/workflows/dfx-action.yml
+++ b/.github/workflows/dfx-action.yml
@@ -10,13 +10,70 @@ jobs:
     runs-on: ${{ matrix.os }}
     name: Test the dfx action (action.yml)
     strategy:
+      fail-fast: false
       matrix:
-        version: ['0.11.1', '0.14.1', '0.14.2-beta.2', 'latest']
-        os: [ ubuntu-latest, macos-latest ]
+        include:
+          - version: '0.11.1'
+            expected-version: '0.11.1'
+            os: ubuntu-latest
+          - version: '0.14.1'
+            expected-version: '0.14.1'
+            os: ubuntu-latest
+          - version: '0.14.2-beta.2'
+            expected-version: '0.14.2-beta.2'
+            os: ubuntu-latest
+          - version: 'latest'
+            os: ubuntu-latest
+          - version: 'auto'
+            os: ubuntu-latest
+          - version: 'auto'
+            dfx-json-dfx-version: '0.11.1'
+            expected-version: '0.11.1'
+            os: ubuntu-latest
+          - version: 'auto'
+            dfx-json-dfx-version: '0.14.1'
+            expected-version: '0.14.1'
+            os: ubuntu-latest
+          - version: 'auto'
+            dfx-json-no-dfx-version: 'true'
+            os: ubuntu-latest
+
+          - version: '0.11.1'
+            expected-version: '0.11.1'
+            os: macos-latest
+          - version: '0.14.1'
+            expected-version: '0.14.1'
+            os: macos-latest
+          - version: '0.14.2-beta.2'
+            expected-version: '0.14.2-beta.2'
+            os: macos-latest
+          - version: 'latest'
+            os: macos-latest
+          - version: 'auto'
+            os: macos-latest
+          - version: 'auto'
+            dfx-json-dfx-version: '0.11.1'
+            expected-version: '0.11.1'
+            os: macos-latest
+          - version: 'auto'
+            dfx-json-dfx-version: '0.14.1'
+            expected-version: '0.14.1'
+            os: macos-latest
+          - version: 'auto'
+            dfx-json-no-dfx-version: 'true'
+            os: macos-latest
+
     steps:
       # To use this repository's private action, you must check out the repository
       - name: Checkout
         uses: actions/checkout@v4
+      - name: Setup
+        run: |
+          if [ -n "${{ matrix.dfx-json-dfx-version }}" ]; then
+            echo "{\"dfx\": \"${{ matrix.dfx-json-dfx-version }}\"}" > dfx.json
+          elif [ -n "${{ matrix.dfx-json-no-dfx-version }}" ]; then
+            echo "{}" > dfx.json
+          fi
       # Install a certain `dfx` version and check if it is properly installed
       - name: Install dfx
         uses: ./
@@ -25,15 +82,15 @@ jobs:
       - name: Check if the proper dfx version is installed
         run: |
           actual_dfx_ver="$(dfx --version)"
-          expected_dfx_ver="dfx ${{ matrix.version }}"
 
-          if [ "$expected_dfx_ver" != "dfx latest" ]; then
-            if [ "$actual_dfx_ver" != "$expected_dfx_ver" ]; then
-              echo "Error: expected dfx version '$expected_dfx_ver', but '$actual_dfx_ver' found"
-              exit 1
-            fi
+          if [ -n "${{ matrix.expected-version }}" ]; then
+              expected_dfx_ver="dfx ${{ matrix.expected-version }}"
 
-            echo "dfx version '$actual_dfx_ver' was installed correctly"
+              if [ "$actual_dfx_ver" != "$expected_dfx_ver" ]; then
+                echo "Error: expected dfx version '$expected_dfx_ver', but '$actual_dfx_ver' found"
+                exit 1
+              fi
+              echo "dfx version '$actual_dfx_ver' was installed correctly"
           else
-            echo "The latest version is '$actual_dfx_ver'"
+              echo "dfx version '$actual_dfx_ver' was installed"
           fi
